CREATE DATABASE IF NOT EXISTS goranking;
USE goranking;

CREATE TABLE IF NOT EXISTS GAMES(id_game INT PRIMARY KEY NOT NULL AUTO_INCREMENT, id_player_1 INT NOT NULL, level_player_1 FLOAT NOT NULL, id_player_2 INT NOT NULL, level_player_2 FLOAT NOT NULL, date_game INT NOT NULL, moves TEXT);

CREATE TABLE IF NOT EXISTS GAMESINFOS(id_info INT PRIMARY KEY NOT NULL AUTO_INCREMENT, id_game INT NOT NULL, type_info INT NOT NULL, value_info TEXT);

CREATE TABLE IF NOT EXISTS PLAYERS(id_player INT PRIMARY KEY NOT NULL AUTO_INCREMENT, current_level FLOAT NOT NULL, trivia_player TEXT);

CREATE TABLE IF NOT EXISTS PLAYERSINFOS(id_info INT PRIMARY KEY NOT NULL AUTO_INCREMENT, id_player INT NOT NULL, type_info INT NOT NULL, value_info TEXT);