// Generated by dia2code
#ifndef __SERVER__H
#define __SERVER__H

#include "view/HttpStatus.h"
#include "view/AbstractService.h"
#include "view/ServiceException.h"
#include "view/ServicesManager.h"
#include "view/CommandeService.h"
#include "view/UtilisateurService.h"
#include "view/Server.h"
#endif
